repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pycqa/pylint
    rev: v3.1.0
    hooks:
      - id: pylint
        name: pylint (Django)
        args: [
            "--load-plugins=pylint_django",
            "--rcfile=.pylintrc"
          ]
        additional_dependencies: [pylint-django]