repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: local
    hooks:
      - id: pylint
        entry: pylint
        language: system
        name: pylint
        types: [ python ]
        require_serial: true
        args: [
            "--load-plugins=pylint_django",
            "--django-settings-module=djangoProject.settings",
            "--rcfile=.pylintrc"
          ]
