# Generated by Django 5.1.6 on 2025-02-22 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Luna", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reading",
            name="hydroponic_system",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="readings",
                to="Luna.hydroponicsystem",
            ),
        ),
    ]
