services:
#  db:
#    container_name: postgres
#    image: postgres:17.3
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      POSTGRES_DB: luna
#    volumes:
#      - db:/data/postgres
#    ports:
#      - "5332:5432"
#    networks:
#      - db
#    restart: always
#    healthcheck:
#      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
#      interval: 30s
#      timeout: 10s
#      retries: 5

  db:
    image: postgres:17.3
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?:POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER?:POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB?:POSTGRES_DB}
    ports:
      - "5432:5432"
networks:
  db:
    driver: bridge

volumes:
  db: