services:
  db:
    image: postgres:17.3
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?:POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER?:POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB?:POSTGRES_DB}
    ports:
      - "5432:5432"

  backend:
    build:
      context: ../.
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER?:POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?:POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB?:POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST?:POSTGRES_HOST}
    ports:
      - "8000:8000"
    depends_on:
      - db
networks:
  Luna:
    driver: bridge

volumes:
  db: